language: node_js
node_js: 12

# S: Build Lifecycle
install:
  - npm install


before_script:
  - npm install hexo-math --save
  - hexo math install
  - npm uninstall hexo-renderer-marked --save
  - npm install hexo-renderer-markdown-it-plus --save

script:
  - git clone --branch=master https://github.com/racheliurui/markdown.git
  - cp -R ./markdown ./source/_posts
  - hexo cl 
  - hexo g -d

after_script:
  - cd ./public
  - git init
  - git config user.name "racheliurui"
  - git config user.email "liuruibnu@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/racheliurui/racheliurui.github.io
